/**
 * Renders the Python twin of the assistant knowledge module.
 *
 * Same content as typescript/src/assistant-knowledge.ts and
 * ui/src/assistant-knowledge.ts — one source (scripts/build-knowledge.mjs),
 * three generated files, enforced by the parity tests.
 */

export function pyLiteral(value) {
  if (value === null || value === undefined) return "None";
  if (typeof value === "boolean") return value ? "True" : "False";
  if (typeof value === "number") return String(value);
  if (typeof value === "string") return JSON.stringify(value); // JSON strings are valid Python literals
  if (Array.isArray(value)) return "[" + value.map(pyLiteral).join(", ") + "]";
  return (
    "{" +
    Object.entries(value)
      .map(([key, item]) => JSON.stringify(key) + ": " + pyLiteral(item))
      .join(", ") +
    "}"
  );
}

export function renderPythonModule({ version, examples, core, basePrompt, catalog, mermaidExamples, mermaidGuide, tooling, reportGuide }) {
  return `"""AUTO-GENERATED by scripts/build-knowledge.mjs — DO NOT EDIT.

Source of truth: schema/abs.schema.json, VOCABULARY.md, examples/*.yaml,
assistant/*.md. Regenerate with: npm run gen:knowledge
"""

import re as _re

ABS_VERSION = ${pyLiteral(version)}

EXAMPLES = ${pyLiteral(examples)}

CORE = ${pyLiteral(core)}

BASE_PROMPT = ${pyLiteral(basePrompt)}

EXAMPLE_CATALOG = ${pyLiteral(catalog)}

TOOLING = ${pyLiteral(tooling)}

REPORT_GUIDE = ${pyLiteral(reportGuide)}

MERMAID_GUIDE = ${pyLiteral(mermaidGuide)}

MERMAID_EXAMPLES = ${pyLiteral(mermaidExamples)}

_MERMAID_MARKERS = ("\`\`\`mermaid", "flowchart", "sequencediagram", "graph td", "graph lr", "graph tb", "graph rl", "graph bt", "classdiagram", "statediagram", "erdiagram", "gantt", "journey")

_ABS_OUTPUT_MARKERS = ("\\"run_id\\":", "\\"rows_total\\":", "\\"row_vars\\":", "\\"steps_matched\\":", "\\"evaluations_total\\":", "\\"chain_evaluations\\":", "\\"observed\\":", "evaluation.result", "behavior.match", "report.written")


def looks_like_mermaid(text: str) -> bool:
    lowered = (text or "").lower()
    return any(marker in lowered for marker in _MERMAID_MARKERS)


def looks_like_abs_output(text: str) -> bool:
    text = text or ""
    return any(marker in text for marker in _ABS_OUTPUT_MARKERS)


def select_examples(query: str, limit: int = 3, max_chars: int = 5000) -> list[dict]:
    """Picks the examples whose tags best match the query. Deterministic; no model involved."""
    q = (query or "").strip().lower()
    if not q:
        return []

    def score(ex: dict) -> int:
        total = 0
        for tag in ex["tags"]:
            if tag.lower() in q:
                total += 3
        for word in _re.split(r"[^a-z0-9]+", ex["name"].lower()):
            if len(word) > 2 and word in q:
                total += 2
        for word in _re.split(r"[^a-z0-9]+", ex["title"].lower()):
            if len(word) > 3 and word in q:
                total += 1
        return total

    scored = [{"ex": ex, "score": score(ex)} for ex in EXAMPLES]
    if any(item["score"] > 0 for item in scored):
        ranked = sorted(scored, key=lambda item: (-item["score"], len(item["ex"]["content"]), item["ex"]["name"]))
    else:
        ranked = sorted(scored, key=lambda item: len(item["ex"]["content"]))

    picked: list[dict] = []
    total_chars = 0
    for item in ranked:
        ex = item["ex"]
        if len(picked) >= limit:
            break
        if picked and total_chars + len(ex["content"]) > max_chars:
            continue
        picked.append(ex)
        total_chars += len(ex["content"])
    return picked


def _yaml_block(ex: dict) -> str:
    return "### " + ex["name"] + ": " + ex["title"] + "\\n\\n\`\`\`yaml\\n" + ex["content"] + "\\n\`\`\`"


def _mermaid_block(m: dict) -> str:
    return (
        "## Mermaid input: " + m["name"] + "\\n\\n\`\`\`mermaid\\n" + m["diagram"] + "\\n\`\`\`\\n\\n"
        + "## ABS output for " + m["name"] + "\\n\\n\`\`\`yaml\\n" + m["yaml"] + "\\n\`\`\`"
    )


def build_system_prompt(query: str = "") -> str:
    """Builds the system prompt: fixed rules + generated reference + the most relevant examples."""
    sections = [
        BASE_PROMPT,
        "# ABS REFERENCE — generated from the normative JSON Schema; if it is not here, it does not exist.",
        CORE,
        "# ABSLANG TOOLING — the CLI that runs these files.",
        TOOLING,
        "# EXAMPLE CATALOG — every example available. The most relevant ones are expanded below.",
        EXAMPLE_CATALOG,
        "# RELEVANT EXAMPLES — complete, valid .abs.yaml files. Use them as reference, adapt to the user's flow.",
        "\\n\\n".join(_yaml_block(ex) for ex in select_examples(query, 3)),
    ]
    if looks_like_mermaid(query):
        sections.append("# MERMAID INPUT — the user pasted a diagram. Convert it directly to ABS using these rules.")
        sections.append(MERMAID_GUIDE)
        for m in MERMAID_EXAMPLES:
            sections.append(_mermaid_block(m))
    if looks_like_abs_output(query):
        sections.append("# ABS RUN OUTPUT — the user pasted a report, event log, or trace. Explain it for QA/PM.")
        sections.append(REPORT_GUIDE)
    return "\\n\\n".join(sections)
`;
}
