// The real browser runner is generated by scripts/bundle.mjs into
// website/public/abs-runner.js. This stub keeps the UI build self-contained;
// the "Run" feature throws a clear error in this local build.
export async function runBrowser(): Promise<any> {
  throw new Error(
    'Runner not available in this local build. Generate it with: node scripts/bundle.mjs'
  );
}
