"""The Python assistant knowledge mirrors the schema and the generated TS/UI modules.

Generated by scripts/build-knowledge.mjs — see typescript/src/__tests__/assistant-prompt.test.ts
for the TypeScript side of the same contract.
"""

import json
from pathlib import Path

from abslang.assistant_knowledge import (
    ABS_VERSION,
    CORE,
    EXAMPLES,
    MERMAID_GUIDE,
    REPORT_GUIDE,
    TOOLING,
    build_system_prompt,
    looks_like_abs_output,
    looks_like_mermaid,
    select_examples,
)

SCHEMA = json.loads((Path(__file__).resolve().parents[2] / "schema" / "abs.schema.json").read_text())


def test_version_matches_schema_title():
    assert ABS_VERSION == SCHEMA["title"].split("v")[-1]


def test_core_covers_every_evaluator_type():
    for evaluator_type in SCHEMA["definitions"]["evaluation"]["properties"]["type"]["enum"]:
        assert evaluator_type in CORE


def test_example_catalog_is_populated():
    assert len(EXAMPLES) >= 10
    for ex in EXAMPLES:
        assert ex["name"]
        assert ex["content"]


def test_tooling_is_always_in_the_prompt():
    prompt = build_system_prompt("quiero un test")
    assert TOOLING in prompt
    assert "abslang run" in prompt
    assert REPORT_GUIDE not in prompt


def test_report_guide_only_when_a_run_output_is_pasted():
    report = '{"run_id": "r_1", "rows_total": 2, "results": []}'
    assert looks_like_abs_output(report)
    assert REPORT_GUIDE in build_system_prompt(report)

    plain = "hola, quiero un test del flujo de reembolsos"
    assert not looks_like_abs_output(plain)
    assert REPORT_GUIDE not in build_system_prompt(plain)


def test_mermaid_guide_only_when_a_diagram_is_pasted():
    assert looks_like_mermaid("sequenceDiagram")
    assert not looks_like_mermaid("quiero un test")
    assert MERMAID_GUIDE not in build_system_prompt("quiero un test")
    assert MERMAID_GUIDE in build_system_prompt("```mermaid\nflowchart TD\n A-->B")


def test_select_examples_prefers_matching_tags():
    picked = select_examples("groundedness against a knowledge base", 2)
    assert any("groundedness" in ex["tags"] for ex in picked)
    assert select_examples("", 3) == []
